### ISSUE TITLE
出一个最简单的新手入门指南

### ISSUE THREAD

**Issue by DeeliN-uno** [SUSTech-CRA/sustech-master-thesis#37]
各位，目前的介绍页面看起来比较简略，让门外汉摸不着头脑，写了些内容后想预览就报错，不像Word那样所见即所得，也不知道该如何设置。

能否出一个最简单易懂的新手入门指南，以帮助那些之前一直使用Word写作的人快速上手？

一个从Word转到此项目的人的典型想法大概是“这个项目已经完成所有格式设置，我只需要知道**在哪个地方填充自己的论文内容**即可，就像填写表格一样，其他的不需要操心”。

另外，如何做Latex的版本控制？对标的是Word的审阅模式。

辛苦各位了，相信弄清楚这些问题可以让这个项目被更多人使用

<img width="448" alt="Snipaste_2022-02-22_15-32-24" src="https://user-images.githubusercontent.com/41354320/155083904-281ea11e-5960-4c60-8069-89e0de31a2a2.png">
。

**Comment by liziwl** [comment]
> 能否出一个最简单易懂的新手入门指南，以帮助那些之前一直使用Word写作的人快速上手？

README部分提到了一个视频可以看看

> 如何做Latex的版本控制？对标的是Word的审阅模式。

1. 直接在 pdf 上标注
2. 使用 todonotes 宏包，这是文档：http://tug.ctan.org/macros/latex/contrib/todonotes/todonotes.pdf

**Comment by DeeliN-uno** [comment]
B站的视频看了，在ShareLatex上可以在线使用，但是在VScode上却无法运行，错误见附件。

VScode上SSH连接了校内的服务器(Ubuntu20.04)，在那上面安装了LATEX WORKSHOP插件，也确认存在xelatex程序。在解压了最新版1.3.9的压缩包后，点开sustechthesis-example.tex后就显示出一些错误，紧接着右下角开始报错，查看日志显示默认使用的是pdfLatex程序。所有文件未作任何修改。

尝试手动点击Recipe: latexmk for ... 后错误日志见附件:

[latexmk_error.log](https://github.com/SUSTech-CRA/sustech-master-thesis/files/8115564/latexmk_error.log)

**Comment by liziwl** [comment]
@DeeliN-uno 第二个选项试过没有？就是GNU make thesis

**Comment by DeeliN-uno** [comment]
感谢提醒，然而还是不能编译，已经点了Clean up然后再点击Recipe: latexmk或者Recipe: GNU，都是Recipe terminated with error

[letexmk_error.log](https://github.com/SUSTech-CRA/sustech-master-thesis/files/8121489/letexmk_error.log)

[GNUmake_erorr.log](https://github.com/SUSTech-CRA/sustech-master-thesis/files/8121490/GNUmake_erorr.log)

[sustechthesis-example.txt](https://github.com/SUSTech-CRA/sustech-master-thesis/files/8121498/sustechthesis-example.txt)

**Comment by liziwl** [comment]
你用的是 apt 装的 texlive-full 吧，我从重现出来了，先注释掉或者删除 sustech-setup.tex 里面 `\bibliographystyle{sustechthesis-numeric}`，这样参考文献会一点小差别。不过也符合国标。我再看看这个问题怎么修。

**Comment by liziwl** [comment]
> https://github.com/zepinglee/gbt7714-bibtex-style#%E7%89%88%E6%9C%AC-v20-%E7%9A%84%E9%87%8D%E8%A6%81%E4%BF%AE%E6%94%B9
> 从 v2.0 版本开始（2020-03-04），用户必须在文档中使用 \bibliographystyle 命令选择参考文献样式， 如 gbt7714-numerical 或 gbt7714-author-year。 在早期的版本中，选择文献样式的方法是将 numbers 或 super 等参数传递给 gbt7714， 而不能使用 \bibliographystyle。 这跟标准的 LaTeX 接口不一致，所以将被弃用。

这是由于 ubuntu apt 安装的 texlive 宏包更新不及时导致的，所需要使用的 `gbt7714.sty` (/usr/share/texlive/texmf-dist/tex/latex/gbt7714) 版本还在 2019/11/20 v1.1.2，然而模版已经使用了 2.0开始引入的接口，所以导致编译错误。

**Comment by liziwl** [comment]
> 你用的是 apt 装的 texlive-full 吧，我重现出来了，先注释掉或者删除 sustech-setup.tex 里面 `\bibliographystyle{sustechthesis-numeric}`，这样可以通过编译了，但是参考文献会一点小差别，不过也符合国标。~我再看看这个问题怎么修。~

另外的解决方案是自己更新 gbt7714.sty (/usr/share/texlive/texmf-dist/tex/latex/gbt7714) 。只要更新这个文件就可以了，https://github.com/zepinglee/gbt7714-bibtex-style/blob/master/gbt7714.sty

**Comment by DeeliN-uno** [comment]
感谢，修改了 `/usr/share/texlive/texmf-dist/tex/latex/gbt7714/gbt7714.sty` 的内容后编译可以通过了。

Cheers!
