### ISSUE TITLE
中文版本的封面字体没有加粗

### ISSUE THREAD

**Issue by AbigailGuo** [SUSTech-CRA/sustech-master-thesis#5]
## 编译环境
编译的系统： Windows 10
TeX 发行版：TeX Live 2019
模板类型： master
模版语言：chinese

## 描述问题
《研究生学位论文写作指南》第 0 页要求 封面字体加粗 而模板编译的结果是 字体未加粗

截图：
[bug1](https://i.loli.net/2021/05/19/VfnxUbsB4WHcyPo.png)

错误日志：
```
Font shape `TU/KaiTi(0)/bx/n' undefined(Font) using `TU/KaiTi(0)/m/n' instead
Font shape `TU/SimSun(1)/bx/n' undefined(Font) using `TU/SimSun(1)/m/n' instead
```
# 解决办法：
https://www.zhihu.com/question/58456658/answer/157120688
在main.tex中的/documentclass中加入AutoFakeBold
···
\documentclass[cs4size,openany,UTF8,AutoFakeBold]{ctexbook}
···

**Comment by liziwl** [comment]
提错项目了，开题项目位于 https://github.com/liziwl/sustech-master-reports
