### ISSUE TITLE
考虑编译时强制将字体嵌入PDF

### ISSUE THREAD

**Issue by ghlkm** [SUSTech-CRA/sustech-master-thesis#55]
原因：字体不嵌入PDF会导致在字体缺失的浏览器或者系统上造成缺失字体的文字显示乱码
可能的参考方案1：强制编译PDF时嵌入字体，  https://www.overleaf.com/learn/latex/Questions/My_submission_was_rejected_by_the_journal_because_%22Font_XYZ_is_not_embedded%22._What_can_I_do%3F
影响：加入字体编译时强制嵌入后， 生成的PDF会变大（影响不大）， 编译速度变慢（可能会对用户影响比较大）

可能的参考方案2：
为用户提供嵌入字体的建议， 比如在README中以及模板中比较醒目的位置提醒用户最终提交时用PDF软件重新打印PDF， 比如用Adobe打开生成的PDF， 并将生成的PDF打印成Adobe PDF, 让用户提交打印好的Adobe PDF

**Comment by liziwl** [comment]
> ## 强制编译PDF时嵌入字体

https://github.com/SUSTech-CRA/sustech-master-thesis/blob/3cca3bfeeffbff34d6de665dad049f74ce28794f/latexmkrc#L6

`xdvipdfmx` 命令已经用了 `-E` 参数（Always try to embed fonts, ignoring licensing flags, etc.）。[xdvipdfmx文档](https://man.archlinux.org/man/extra/texlive-bin/xdvipdfmx.1.en#E)

> ## 嵌入字体的建议

### matplotlib 画图
此外，我发现如果插入 matplotlib 生成的 eps 图，pdf 中的字体类型是Type3，不会显示被嵌入。可能需要建议使用已经嵌入字体的 pdf 类型插图。以下是使用 matplotlib 生成嵌入 Type1类型字体的PDF文件的命令。

```python3
import matplotlib.pyplot as plt

# 设置默认字体格式，默认使用 Type1 字体
plt.rc('font', family='Times New Roman', size=14)
plt.rcParams['pdf.fonttype'] = 42
plt.rcParams['ps.fonttype'] = 42

# 省略 matplotlib 画图命令...

# 保存图片为 PDF
plt.savefig('FIGURE_NAME.pdf', bbox_inches='tight', pad_inches=0)
# plt.show()
```

* [Avoiding Type 3 fonts in matplotlib plots](http://phyletica.org/matplotlib-fonts/)
* [Paper中含有Type3的字体，需要修改为Type1字体](https://blog.csdn.net/clksjx/article/details/115216122)

### MS PowerPoint 画图
1. 选择 **导出 -> Adobe PDF** 格式，而不是保存，即可嵌入字体。

**Comment by ghlkm** [comment]
1. 补充MATLAB的样例
2. 考虑增加一个类似document的文件， 将常见问题以及一些使用建议（如图片应使用PDF格式）放入document中
3. 一个疑问：如果一个PDF图片原本字体未嵌入， xdvipdfmx 是否也会将图片的字体嵌入

**Comment by liziwl** [comment]
> 如果一个PDF图片原本字体未嵌入， xdvipdfmx 是否也会将图片的字体嵌入？

不会嵌入。补救措施，该 PDF 插图使用 Adobe Reader 打印。

1. 打开 pdf 文件后，点击文件 -> 打印；
2. 选择打印机名称到Adobe PDF->属性->默认设置【标准】-> 编辑 -> 字体，然后将“字体来源”中的所有字体都添加到“总是嵌入”边框；
3. 取消勾选：“仅依靠系统字体：不使用文档字体”；
4. 点击打印。

然后插入已经嵌入字体的插图。

**Comment by liziwl** [comment]
@ghlkm https://github.com/SUSTech-CRA/sustech-master-thesis/wiki 可以直接在这里写

**Comment by ghlkm** [comment]
总结：
1. 图片的字体嵌入可以用adbobe 打印
2. 模板当前支持整个文档的文字或公式的字体嵌入
3. adobe pro支持将未嵌入字体的PDF文档包括文档里的图片PDF的字体嵌入https://blog.csdn.net/benchuspx/article/details/120070051
