### ISSUE TITLE
关于图表距离的修复

### ISSUE THREAD

**Issue by liziwl** [SUSTech-CRA/sustech-master-thesis#56]
#54 这个依旧没有正确修复，~~似乎是patchcmd没有应用~~。

**Comment by liziwl** [comment]
https://tex.stackexchange.com/questions/588462/how-to-remove-extra-space-at-the-bottom-of-tables-and-figures/588484

**Comment by liziwl** [comment]
@iydon 继续在这边讨论吧。

**Comment by liziwl** [comment]
> ### 方案2
> ```
>   \AfterEndEnvironment{figure}{\vskip-12bp}
>   \AfterEndEnvironment{table}{\vskip-6bp}
> ```

这个问题是，如果参数不为 h 就会出现一下情况。
<img width="768" alt="image" src="https://user-images.githubusercontent.com/23000702/163715626-99b1cf69-5e0f-4a3a-a3e6-dc1f8cb42a94.png">

 使用 `\nointerlineskip` 一样会有类似的问题。

**Comment by iydon** [comment]
https://github.com/SUSTech-CRA/sustech-master-thesis/blob/d1fcf36b2fedd5f90f63eb44e3c0337fd3b6590e/sustech-setup.tex#L145

问题来自于 `minted` 宏包中导入了 `lineno` 宏包，`lineno` 宏包中貌似对 penalty 的修改挺多的，但是涉及到 TeX primitives，所以具体是哪些行还没有找出来（debug 思路就是明面上的代码没问题，那么问题可能是引入的宏包带来的，所以依次检查 RequirePackage 与 usepackage）。

清华的模板中使用 `minted` 宏包依然会有浮动体上下间隔不一致的情况，以下为通过简单遍历后发现的导入了 `lineno` 的文类或者宏包。未完善的遍历脚本见 [gist](https://gist.github.com/iydon/9571a9d25e4ab4ef4860f39b77b63e29)。

```
BMSTU-IU8.cls
aastex631.cls
ametsoc.cls
ascelike.cls
asmeconf.cls
asmejour.cls
beilstein.cls
buctthesis.cls
cc.cls
cje.cls
einfart.cls
gammas.cls
grant.cls
hepthesis.cls
hithesis.cls
hitszthesis.cls
iwhdp.cls
langscibook.cls
lectures.cls
legislation.cls
lyluatexbase.cls
minimart.cls
minimbook.cls
pdfArticle.cls
revtex4-1.cls
revtex4-2.cls
simplivre.cls
simurgh-doc.cls
skdoc.cls
uothesis.cls
verifica.cls

10-IU8-titlepage.sty
cclayout.sty
dline-shipunov.sty
dtx-style.sty
edcntwd0.sty
ednotes.sty
edtable.sty
ekdosis.sty
feupphdteses.sty
ffcode.sty
fvextra.sty
linenoamsmath.sty
local.sty
mftinc.sty
mindflow.sty
minimalist.sty
minorrevision.sty
minted.sty
nucleardata.sty
plantuml.sty
puyotikz.sty
pythontex.sty
runcode.sty
stdpage.sty
ver-doc.sty
vertbars.sty
vplref.sty
```

**Comment by iydon** [comment]
`lineno` 中致使图表位置不正确的代码片段（简化后）如下，我目前还理解不了原理（output routine），所以没找到解决方案。

```latex
\let\@tempa\output
\newtoks\output
\output=\expandafter{\the\@tempa}
\@tempa={\the\output}
```

**Comment by liziwl** [comment]
> `lineno` 中致使图表位置不正确的代码片段（简化后）如下，我目前还理解不了原理（output routine），所以没找到解决方案。
> 
> ```
> \let\@tempa\output
> \newtoks\output
> \output=\expandafter{\the\@tempa}
> \@tempa={\the\output}
> ```

`lineno` 包已经17年没更新了，太久了。如果修复方式不太容易的话，可以可以给 `minted` 提需求要他们修算了。

**Comment by liziwl** [comment]
https://tex.stackexchange.com/questions/40863/parskip-inserts-extra-space-after-floats-and-listings/40896#40896 看来这个问题有点历史了。

**Comment by liziwl** [comment]
补充一下向上游提的问题 https://github.com/tuna/thuthesis/issues/614 ，也没有很好的解决方式。
目前的解决方式是建议使用 `listings` 而不是会有兼容性的 `minted` 格式化代码，并针对  `minted` 包的引入警告。
