### ISSUE TITLE
在Overleaf中编译超时

### ISSUE THREAD

**Issue by Nuofan-SUSTech** [SUSTech-CRA/sustech-master-thesis#69]
![image](https://github.com/SUSTech-CRA/sustech-master-thesis/assets/80809557/766820c5-9080-4274-a3ca-8d4b9f6fc2a4)
Overleaf加了编译时间的限制，提示编译超时了
想问一下有没有什么办法优化一下编译速度嘛？

**Comment by liziwl** [comment]
暂时没有好的优化方式，提示是接近编译超时极限，还没有超时。

**Comment by note286** [comment]
建议更换平台，比较建议本地使用，在线的话可以使用TeXPage。非要Overleaf，可以选择使用`\input`来部分编译。

**Comment by Nuofan-SUSTech** [comment]
感谢回复，改用了CRA的Sharelatex了。不用本地是因为有好多个设备，想用网页的服务，这样方便同步管理

**Comment by note286** [comment]
本地可以使用同步盘或者git来管理。当然，这都是用户的选择，怎么舒服怎么来。

**Comment by Nuofan-SUSTech** [comment]
> 本地可以使用同步盘或者git来管理。当然，这都是用户的选择，怎么舒服怎么来。

感谢回复，是很好的建议。但用网页确实会舒服一点，而且也方便分享给老板批改 ：）
