### ISSUE TITLE
硕士学位开题报告中文模板LaTeX与Word存在一处字号不一致

### ISSUE THREAD

**Issue by RyderCRD** [SUSTech-CRA/sustech-master-thesis#72]
## 编译环境
编译的系统：Overleaf
TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
模板类型：master
模版语言：chinese

## 描述问题
《南方科技大学硕士学位论文开题报告中文模板》（Word）中”南方科技大学“六字的字号（楷体，小一）相较于此模板中 sustechthesis-example-report.tex 的编译结果更大。是否应该依据截图对.cls进行相应修改，以保持与word模板的一致？

截图：
![image](https://github.com/SUSTech-CRA/sustech-master-thesis/assets/39330401/4ef899bd-96b4-496a-b2e7-3d4ff57dbb35)

![image](https://github.com/SUSTech-CRA/sustech-master-thesis/assets/39330401/8e4c3a87-c892-4d3b-862a-b2eee1de7a0c)

**Comment by liziwl** [comment]
![image](https://github.com/SUSTech-CRA/sustech-master-thesis/assets/23000702/d95a8006-1010-493f-b59a-56d2ef0bdfc3)
我这边-2看起来字体一样大，只是字间距不太一样

**Comment by RyderCRD** [comment]
我用打印机打印出来对着光验证了一下：
![image](https://github.com/SUSTech-CRA/sustech-master-thesis/assets/39330401/21c700cf-7c12-4eb3-b7ec-5d1e1020f56a)
![image](https://github.com/SUSTech-CRA/sustech-master-thesis/assets/39330401/b14fdb26-1cc9-41cb-9ecc-82d9c3ff58af)

**Comment by RyderCRD** [comment]
说反了哈哈，上面小的是-2

**Comment by liziwl** [comment]
《南方科技大学硕士学位论文开题报告中文模板》在哪里下载的？我确认下

**Comment by RyderCRD** [comment]
确实，我搜索了一下，如下两个结果中的《中文模板》中 “南方科技大学” 都是-2的字体，与本模板一致：
![image](https://github.com/SUSTech-CRA/sustech-master-thesis/assets/39330401/0432f3d9-0b28-49fa-890f-62ce0fde913f)

而我前面所提到的《中文模板》实际上来源于12月8日院系给我们发的开题答辩通知邮件的附件：

![image](https://github.com/SUSTech-CRA/sustech-master-thesis/assets/39330401/6ca04742-4085-48c5-ab1d-c81797718345)

![image](https://github.com/SUSTech-CRA/sustech-master-thesis/assets/39330401/98984c9e-938d-4dd8-8a31-f0246ed740c1)

我查看了这三份《中文模板》的最后保存时间，其中邮件附件是最新的：

![image](https://github.com/SUSTech-CRA/sustech-master-thesis/assets/39330401/f0ae91f3-78e4-42b8-9f6a-054e9954a39a)

并且问了一下隔壁学院同学，她收到的邮件附件与我一致，《中文模板》中 “南方科技大学” 是-1的字体。我想或许是学校22年9月悄悄修改了《中文模板》。今年 未来网络研究院 和 创新创意设计学院 所发的开题邮件中都附了此份《中文模板》，但是我们两个院规模都比较小，尚不清楚其它院系是否与我们一样。

**Comment by RyderCRD** [comment]
[附件2-1 南方科技大学硕士学位论文开题报告中文模板.docx](https://github.com/SUSTech-CRA/sustech-master-thesis/files/14007553/2-1.docx)

**Comment by liziwl** [comment]
已修改
