### ISSUE TITLE
开题报告编辑

### ISSUE THREAD

**Issue by sunward-ZhouZhihao** [SUSTech-CRA/sustech-master-thesis#73]
我将今天发布的最新开发版模板导入texpage.com中编译，在sustech-setup.tex里修改"type = proposal", 编译之后确实大标题变成了【***开题模板】，但其他委员会名单和原创性声明一应俱全，，，，我想问一下，用此模板编写开题报告须提前将sustechthesis-example.tex文件删除再上传至texpage.com中吗？（在texpage.com中删除sustechthesis-example.tex失败，提示是主程序不能删😂）

**Comment by liziwl** [comment]
右上角设置可以换
![image](https://github.com/SUSTech-CRA/sustech-master-thesis/assets/23000702/edf8901f-8116-4981-a165-95ddb3677323)

![image](https://github.com/SUSTech-CRA/sustech-master-thesis/assets/23000702/36f28172-f6f9-48e5-9e9f-5105f6f0fbce)
